POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doerr@example.com",
  "password": "password1234"
}

###
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name" : "Admin",
  "email": "admindb@example.com",
  "password": "admin1234",
  "role": "admin"
}

### 
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "name" : "owner123",
  "email" : "ownerresto123@example.com",
  "password": "owner1234",
  "role": "owner"
}

### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email" : "john.doerr@example.com",
    "password": "password1234"
}

### Login Admin
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "admindb@example.com",
  "password" : "admin1234"
}

### Login Owner
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "email" : "ownerresto123@example.com",
  "password" : "owner1234"
}

### Logout Current user
POST http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im93bmVycmVzdG8xMjNAZXhhbXBsZS5jb20iLCJzdWIiOiJhM2Q4NmU5Mi04NzEyLTQ3MjgtODA0ZS1jZWFmNjEzMTA5YWIiLCJyb2xlIjoib3duZXIiLCJpYXQiOjE3NTIwMjc3ODcsImV4cCI6MTc1MjAzMTM4N30.X8ALbOnAJwzQZOR4CaMidZ1-efTO3HgIHvHCxu2Mt0w

###
GET http://localhost:3000/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4uZG9lcnJAZXhhbXBsZS5jb20iLCJzdWIiOiI2YzY3NjJjYi03ZWJhLTQxNTgtOTczMS01YzY2M2EwY2EyNTEiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE3NTIwMzQwNzUsImV4cCI6MTc1MjAzNzY3NX0.268TpLOqqWRU3tcj70ACjaB33zxHUvtJG3zns2266RI
Accept: application/json